extends:
  - standard-with-typescript
  - react-app
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
rules:
  comma-dangle: [error, always-multiline]
  '@typescript-eslint/indent': [error, 4]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/consistent-type-assertions': off
  '@typescript-eslint/promise-function-async': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-invalid-void-type': off
